dist: xenial

language: go


go:
  - 1.12.x


before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run ./pkg/controller/memcached/memcached_controller.go
